"""add filename to URLMap

Revision ID: 340fbd70d9d0
Revises: dc6f1f112264
Create Date: 2025-07-22 15:04:03.321712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340fbd70d9d0'
down_revision = 'dc6f1f112264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
